### ISSUE TITLE
Bring Back The Code

### ISSUE THREAD

**Issue by TobleMiner** [defuse/swatd#7]
Merge the code back to master. If people haave a firewire port on their systems they should know about the risks. Deleting data automatically based on sensor data is not illegal in a lot of countries. So there can't be serious concern about legal stuff.

**Comment by adamcaudill** [comment]
In many places, such an act would be considered destruction of evidence, which has significant consequences. In the US, destroying data in a police raid would be Obstruction of Justice - a very serious change even if not changed with anything else.

The use of the software by itself, even if not tripped, could be used as evidence that a person intended to obstruct justice in a trial. Use should be very carefully thought through, with the legal risks fully understood.

If a person is doing something that places them at risk of a police raid, the use of this software will likely only add new (serious) charges.

**Comment by defuse** [comment]
A lawyer (but not my lawyer) on HN said that using this would most likely result in obstruction of justice charges, even if you are innocent: https://news.ycombinator.com/item?id=8935433

I'll admit that moving the code to a different branch probably isn't the best way to deal with this. I think a better thing to do would be:

1. Move the code back to master.
2. Keep the name "SWATd" (since otherwise I'd have to change the repo's name, and people would start finding forks with google searches).
3. Re-write the readme to just state what it does, without describing any use cases.
4. Add a section explaining that it's historical purpose was to defend against law enforcement (explaining the name), and warn why that's probably a bad idea.

Thoughts?

**Comment by TobleMiner** [comment]
This sounds like a far better idea.

**Comment by defuse** [comment]
By the way, the reason this thing is useful in the first place is just *one* feature: 

A sensor only fails when it *transitions* from working to not working, i.e. it must have been seen working at least once in order for a failure to count. That's why it's different/better than just running a cron script to check the sensor. That's the property you want to have when the action you'll take is potentially destructive, or if you want to be notified when things "go down" and not just every time a check confirms that they "are down". 

There are other legitimate places where that property is useful, but protecting yourself from cops shouldn't be this thing's raison d'etre.

**Comment by defuse** [comment]
Okay, I re-added the code and rewrote the README to de-emphasize its use as anti-law-enforcement tool. What do you think of it now?

**Comment by bfontaine** [comment]
You might also want to rephrase the GitHub project description (which appears just after its title):
![capture d ecran 2015-01-24 a 18 21 38](https://cloud.githubusercontent.com/assets/1334295/5888196/df4aac68-a3f5-11e4-886a-95caee0d1060.png)

**Comment by defuse** [comment]
Updated the project description, thanks @bfontaine

**Comment by TobleMiner** [comment]
There you go! That's a lot better now.

**Comment by TobleMiner** [comment]
You should still fix the the buffer overflow and the script though.

**Comment by defuse** [comment]
Yep, fixed those.

**Comment by TobleMiner** [comment]
I guess that's fixed now
